# Generated by Django 3.1 on 2020-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockupload',
            old_name='file',
            new_name='uploaded_file',
        ),
        migrations.AddField(
            model_name='videosession',
            name='session_type',
            field=models.IntegerField(choices=[[1, 'TRAVEL'], [2, 'WEDDING'], [3, 'BUSINESS'], [4, 'INTRO']], default=4),
        ),
    ]
