# Generated by Django 3.1 on 2020-08-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_videosession_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='final_video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
